### ISSUE TITLE
sublimehaskell on a standalone main.hs complains about ghc-mod even when enable_ghc_mod is set to False

### ISSUE THREAD

**Issue by cartazio** [SublimeHaskell/SublimeHaskell#249]
on a self standing `main.hs` file, even though my sublime haskell config is currently 

```
{
    "add_to_PATH":
    [
        "/Users/carter/.cabal/bin",
        "/Users/carter/.install-ghc/ghc-7.10.3/bin",
        "/Users/carter/bin"
    ],
    "auto_build_mode": "normal",
    "auto_completion_popup": true,
    "enable_auto_build": true,
    "enable_ghc_mod": false,
    "enable_hdevtools": false,
    "enable_hsdev": false,
    "haskell_build_tool": "cabal"
}
```

i get the following warning/error: 

```
SublimeHaskell: ghc-mod was not found!
It is used for LANGUAGE and import autocompletions and type inference.
Try adjusting the 'add_to_PATH' setting.
You can also turn this off using the 'enable_ghc_mod' setting.
```

seems like I'm probably hitting a corner case of all the lovely new work thats been going on :)

**Comment by mvoidex** [comment]
:) I have to test it without enabled hsdev

**Comment by tobia** [comment]
I had the same issue. I'm going through some basic tutorials and for the time being I have no intention of using linting or such, so I tried to disable the tools in my user settings file:

    {
        "enable_hdevtools": false,
        "enable_ghc_mod": false,
        "enable_hsdev": false
    }

Nonetheless, SublimeHaskell kept bugging me on every save. So I changed strategy and disabled the actual actions, which seems to work:

    {
        "enable_auto_check": false,
        "enable_auto_lint": false
    }

So I don't know if this is issue is actually a bug, but at least it needs a different error message, because right now it's slightly misleading:

    ...
    You can also turn this off using the 'enable_ghc_mod' setting.

**Comment by tobia** [comment]
I give up. SublimeHaskell keeps spamming me with console messages every time I open Sublime or do other things, complaining that I don't have this or that haskell command, even when I'm not working on Haskell files. It's really distracting.

**Comment by mvoidex** [comment]
Sorry for delay, i had no time. I'll try to fix it soon

**Comment by mvoidex** [comment]
Which version of ST are you using: ST2 or ST3?

**Comment by mvoidex** [comment]
@cartazio you have `enable_auto_check` and `enable_auto_lint` set to `True`, that's why it tries to check/lint a file. Nevertheless, current error message is meaningless, but what would be better:
* don't do anything (no messages and no check/lint as `hsdev` and `ghc-mod` are disabled)
* show message like this: "you have disabled hsdev and ghc-mod, but still have check/lint enabled, disable it to hide this message"

@tobia can you paste here your sublimehaskell settings? With your settings (disabled hsdev/ghcmod and check/lint) i don't get into this issue

P.S. on last ST i have an sublimetext issue, it doesn't reload modified .sublime-settings, so i have to restart sublime

**Comment by mvoidex** [comment]
@cartazio i've removed panel error message and added different message on status bar instead
try if this fixes your issue

**Comment by cartazio** [comment]
this probably is fixed / havent noticed it lately
