### ISSUE TITLE
Insert import for symbol is silent failed

### ISSUE THREAD

**Issue by t-yng** [SublimeHaskell/SublimeHaskell#271]
I would be happy if you help me.

Nothing was inserted when I tried to Insert import for symbol, and I could not get the error message.

I sacceeded to do the code written  in README.md, so I don't know the reason I failed.
https://github.com/SublimeHaskell/SublimeHaskell/blob/master/Commands/InsertImport.gif

Enviroment
- OS X El Capitan 10.11.2
- Sublime Text Build 3114

The code I failed.
![2016-06-17 0 17 09](https://cloud.githubusercontent.com/assets/11068883/16122579/966e1f2a-3422-11e6-9aa7-eb6bfa11d1f1.png)

 the result after executing Insert import.
![2016-06-17 0 17 12](https://cloud.githubusercontent.com/assets/11068883/16122587/9aa52e9e-3422-11e6-90cc-64f04e970fa3.png)

**Comment by mvoidex** [comment]
That's because this command tries to add import statement somewhere near other imports.
We have to find right place where to insert single import.
It's a bug of course, but command should work if you have at least one import.
Also, note, that unless you set `lint_check_fly` to `true` (it's experimental and i don't recommend doing this when you edit some huge files/projects), file will be rescanned only on save. It's necessary for this command to work correctly.

**Comment by t-yng** [comment]
Thank you for your answer.  
I could Insert Import if I have at least one import.
I hope to solve this problem.

**Comment by bscottm** [comment]
SBF in the forthcoming release next week.

**Comment by bscottm** [comment]
@t-yng: Fixed in 2.0.0 release.
