### ISSUE TITLE
SH inhibits standard ST completions even when inhibit_completions: false

### ISSUE THREAD

**Issue by tobia** [SublimeHaskell/SublimeHaskell#322]
How to reproduce:

1. Open any file where SH is getting proper predictions from hsdev: for example, if you type `put` the popup menu starts with `putChar :: Char -> IO ()`
2. Type `myVeryLongFuctionName :: Int -> Int` and newline
3. Type `my`

Expected outcome: the popup menu should contain `myVeryLongFuctionName` as it would if SH was not installed, indeed it should ***start*** with that item.

Actual outcome: the completion menu contains `mempty :: Monoid a => a` and other stuff, but the name of the function you are defining is nowhere to be found.

**Comment by bscottm** [comment]
@tobia: Would you be able to test my `bscottm/SublimeHaskell` `master` branch. I haven't merged it with `SublimeHaskell/SublimeHaskell` because it's a big change -- the results of `pylint` code auditing. I'm reasonably confident that the audit result is stable, but testing is needed.

I tested your use case and it appears to be fixed. However, I'm interested in what else might be broken in terms of autocompletion.

**Comment by bscottm** [comment]
@tobia: Can you test with the current release on PackageControl (1.2.1)?

**Comment by bscottm** [comment]
@tobia: Closing. Feel free to reopen if necessary.
