### ISSUE TITLE
Default installed version of hsdev is unsupported

### ISSUE THREAD

**Issue by xeoneux** [SublimeHaskell/SublimeHaskell#329]
I got this error after I installed SublimeHaskell:

SublimeHaskell: hsdev version is incorrect: 0.2.3.1
Required version: >= 0.2.0.0 and < 0.2.3.0
Update it by running 'cabal update' and 'cabal install hsdev'

To supress this message and disable hsdev set 'enable_hsdev' to false

**Comment by filostrato** [comment]
Just got the same, current default version of hsdev is 0.2.3.2.

**Comment by bscottm** [comment]
@xeoneux: I've bumped the version number and I'm testing the fix. The current problem is that `hsdev` 0.2.3.2 does not exit when SublimeText exits. Need to fix that before releasing.

This wasn't as simple as just updating the version number. The command line arguments have to be patched differently due to a change in the `simple-log` package (I was having fun with 'log politics' -- a very Soviet era notion, but you likely weren't old enough to remember the Soviet era.)

@mvoidex: The 'link' command should still cause the `hsdev` to exit when the last client connection closes?

**Comment by bscottm** [comment]
@mvoidex: 'link' still works. `hsdev` exits after the last client, if a local server.

@xeoneux: Waiting for packagecontrol.io to pick up the new release tag, 1.2.2. When it does, update will follow with a fix to this issue.

**Comment by bscottm** [comment]
@xeoneux: Is the plugin working for you? If so, can I close this issue?

**Comment by xeoneux** [comment]
@bscottm yes it is! Thanks 😸

**Comment by mvoidex** [comment]
> The 'link' command should still cause the hsdev to exit when the last client connection closes?

Am i missing smth, why 'still'? It's desired behavior. Yes, it should

**Comment by bscottm** [comment]
@mvoidex: Nope. I was doing something dippy at the time -- had to move some code around to make the change to `hsdev` command line arguments less awkward and I moved too much.
