### ISSUE TITLE
Browse Declarations locks up sublime

### ISSUE THREAD

**Issue by dten** [SublimeHaskell/SublimeHaskell#359]
At least it does for me... I can't figure out exactly what but it seems like some kind of UI lock from a background thread or something along those lines.

I'm on Windows x64 build 3144

**Comment by bscottm** [comment]
Compiled `hsdev` with GHC 8.0.2, by any chance?

I can't really put my finger on the exact problem yet, but I suspect there was a change in the 8.0.2 runtime that doesn't completely flush network buffers. `Browse declarations` is basically left waiting for the last packet, which never arrives. And, because this function executes in the main thread, it locks up ST3 until killed.

Recompile with GHC 8.0.1 and things work reliably.

**Comment by bscottm** [comment]
@dten: I'm honestly puzzled because I can get SH to lock up on browsing declarations, randomly. Will pore over the ST3 forum to see if there's a previous issue with show_quick_panel.

**Comment by dten** [comment]
Yes 8.0.2 is used. 
It didn't lock if i comment out the show_quick_panel line though which to me implies it's not hsdev cause all the hard work should be finished the line before if I'm not mistaken

**Comment by bscottm** [comment]
@dten: Breakage in `show_quick_panel` is something I can't really fix, since it's part of the Sublime API. I initially suspected 8.0.2 because that's when other wackiness showed up (and I was getting incomplete responses from `hsdev`.)

Will continue to diagnose.

**Comment by bscottm** [comment]
@dten: This is very intermittent and the ST fora don't provide much insight. For sure, commenting out `show_quick_panel` stops the hang, but that's not really the solution because the whole point is to be able to browse declarations, which requires the quick panel. I'm not going to close the issue, but I'm not really going to devote many cycles to diagnosing it while wringing out bugs in the 2.0.x series.

**Comment by bscottm** [comment]
@dten: Please upgrade to 2.1.7. I think I've solved the hang problem (see #377 and #373). SublimeHaskell needed to read more from the socket and create a bigger raw request buffer because `decode('utf-8')` failed. Likely the incomplete reads were also a problem here as well.

**Comment by dten** [comment]
I'll give it a try

**Comment by bscottm** [comment]
@dten: Any lockups?

**Comment by bscottm** [comment]
@dten: Assuming no new issues, issue is fixed. Feel free to reopen.
