### ISSUE TITLE
prettify_on_save no longer works after 2.1.9

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#379]
At version 2.1.9 `prettify_on_save` broke down. Currently the method in `indenters.py` does not ever get called. Furthermore, enabling `"component_debug": ["event_viewer"]` in the settings shows that [this line](https://github.com/SublimeHaskell/SublimeHaskell/compare/76d612a3a1871d33912c22bf01fbb177a8b95cbd...5fa12f340dc31f05209790663c48871512638690#diff-a60c68ddbe99e0f0c5fa6b994591bdb5R121) does not get called at all.

I'm currently running SublimeHaskell 2.1.9 w/ ST3 b3143 under fully updated Manjaro Linux.

**Comment by bscottm** [comment]
@Pastafarianist: Yes and s/b fixed in 2.1.10 (there was a 2.1.9.1 and 2.1.9.2, but PackageControl apparently only copes with three digit version numbers... <sigh>)

The problem: The ST3 developers don't put version numbers in their API. When I saw the `ViewEventListener` class more fully documented, I assumed (rather incorrectly) that the API was valid for the currently released and stable version, Build 3146. Noooooo. The "enhanced" API is only valid for Builds 3155 and onward.

Had to roll back a little bit of refactoring. 2.1.10 should fix this.

**Comment by bscottm** [comment]
&lt;sigh&gt;. Another race against the source inspector. Working on a better fix...

**Comment by Pastafarianist** [comment]
Works again on 2.1.10. Thanks for quickly noticing and fixing the issue.

**Comment by bscottm** [comment]
@Pastafarianist: I really hope that 2.1.14 fixes "but good". Frustrating, it is. But I do appreciate your help with trying to make _SublimeHaskell_ a usable Haskell development environment.
