### ISSUE TITLE
=<< is not always rendered as a ligature with Fira Code

### ISSUE THREAD

**Issue by Pastafarianist** [SublimeHaskell/SublimeHaskell#385]
See https://github.com/tonsky/FiraCode/issues/534, especially the last comment. 

Without `"use_improved_syntax": true` the problem does not seem to manifest. With that option on, it seems to manifest randomly, and I don't see any pattern. I've tried multiple files: sometimes `=<<` does turn into a ligature, and sometimes it doesn't. I've even been able to produce the following:

![image](https://user-images.githubusercontent.com/1315874/34542924-a6532d46-f0ef-11e7-9cef-21bb9b234cd7.png)

i.e. I opened a file that already contained `=<<` (which were rendered incorrectly), then typed another one, and that last one turned into a ligature.

**Comment by bscottm** [comment]
@Pastafarianist: Yup, the Haskell-SublimeHaskell.tmLanguage ("improved" syntax) does have a pattern match for `-*=<`, which is highlighted as an operator. Not sure how or what to fix, since I'm reasonably sure that was a reason. I'm not sure what the intent was, since I've really been more of a maintainer than author. :-)

If I can get past things like prettifier bugs... I can start looking at upgrading the syntax definitions for the "improved" syntax. (Just yanking your chain.)

**Comment by bscottm** [comment]
It looks like converting the ST2 improved syntax to the ST3 format may have fixed this issue. I've associated the issue with the next release, which will close the issue. Reopen if you still see incorrectly rendered ligatures.

**Comment by bscottm** [comment]
@Pastafarianist: Hopefully addressed. The highlighting definitions are a bit tricky. I'll keep an eye out for breakage.
